spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '1234'

token:
  expiration_time: 864000000 
  secret: 'user_token_native_application'

gateway:
  ip: 172.18.0.3
  
order_service:
  url:  http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.