spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBQZAKKou3aVx1ydGFbBlV4IYGVrzvTgd0Mq0rXKGwK5V4UhwP/d+VbUEWDI8qui/mupYjvI0mHnwrEeu/qtK+wHfDrnvpWiAMMjRkj62GcgHSv1vWMFpc/GAe26KttVlQf/fslmhQhOPaeORPLWN0omJzzmoWLLwTtrWKact1DUs5AWX+nbu7pC2mYzyqi0E8/1Ib1aI7Emhiu1EGUbu25G93YiN05tMdquCZE6Um4g4+neRFaSF0c1zkoPn08VKZ/dU+OxsGymie1Dup8pJYNUHMzd0Js/s1yaQaYo3yPMn0zJ5Ym67AyrxQ/2oIg6pIbAVqrdbWyDbGYnoD4rO7iyTD/4eaEk52BajTlJuW7JzcY1tidJ7Ko3beoynTpkH0='

token:
  expiration_time: 864000000 
  secret: '{cipher}AQBb+pWf2ZinbMeNSu40tLRLiU7T3F4JbQILua+wcmCXb9ZJ563ykzosO+7+J6EkTcPRRIBqC1RCCKhsi8u1rHwzD7G/X3IPeDYz0iJnRnPs1jdWHtya6ZmHYOI87oAc2ZeksKR+TB8f23EcDTbhZOnuaLCxErhbxiLB7FPs96g5Zh+d7/sgC2LNcs7OokvlsOgJ8PKjW46KtpAUntD4zGxWSkBPwW/Ct/VQl6lyLsatF7g2ooSe+UKfQ5yu0WNBZm34g3GL9Ub1fMUjN7pK7Asf1NSPRYYPGz0JhGOa2vJRJf1HY2uxGqFTZwjSpidAz51oe8ygI5hUD39Rd2P02HYTjk0/T06SKj3ysAx1Vgqein1jeG2Y0ft/UnoCU+wPnFRnmjW8C0qOZrqbMd7LlIXK'

gateway:
  ip: 172.18.0.3
  
order_service:
  url:  http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.